name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  tests:
    name: PHP ${{ matrix.php }} - ${{ matrix.deps }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.0]
        deps: [hightest]
        include:
          - php: 7.4
            deps: lowest
    steps:
      - uses: zenstruck/.github@php-test-symfony
        with:
          php: ${{ matrix.php }}
          deps: ${{ matrix.deps }}

  code-coverage:
    uses: zenstruck/.github/.github/workflows/php-coverage-codecov.yml@main
    with:
      php: 8

  composer-validate:
    uses: zenstruck/.github/.github/workflows/php-composer-validate.yml@main

  cs-check:
    uses: zenstruck/.github/.github/workflows/php-cs-fixer.yml@main
